To Do List:-

- Add to analysis:- 
    CAPM Model 
    Bankruptcy Risks
    Perfect stock allocation of the 30 stocks in a portfolio
    
- Visualization in webapp

In [2]:
import pandas as pd
import numpy as np
import math
import scipy.stats as stats
import json
import requests

from functools import reduce

from matplotlib import pyplot as plt

import datetime as dt
from datetime import datetime, date, time, timedelta
from dateutil.relativedelta import relativedelta

from config import api_token

In [3]:
# Web Scrape List of Dow Component Stocks from Yahoo Finance

dow_components_url = 'https://finance.yahoo.com/quote/%5EDJI/components?p=%5EDJI'
dow_components_table = pd.read_html(dow_components_url)[0]

dow_components_table

,Symbol,Company Name,Last Price,Change,% Change,Volume
0,AAPL,Apple Inc.,299.74,-0.06,-0.02%,12971978
1,MSFT,Microsoft Corporation,158.91,-0.12,-0.08%,7457261
2,JNJ,Johnson & Johnson,143.96,-0.14,-0.09%,3032607
3,PFE,Pfizer Inc.,38.83,-0.05,-0.13%,8611736
4,AXP,American Express Company,124.30,0.24,+0.19%,603575
5,V,Visa Inc.,189.76,0.57,+0.30%,1606537
6,PG,The Procter & Gamble Company,123.17,0.42,+0.34%,1947690
7,KO,The Coca-Cola Company,54.46,-0.21,-0.38%,2282629
8,IBM,International Business Machines Corporation,134.70,0.60,+0.45%,1323022
9,MCD,McDonald's Corporation,201.41,-0.92,-0.45%,1274017
10,UTX,United Technologies Corporation,152.98,-0.70,-0.46%,565727
11,NKE,"NIKE, Inc.",102.35,0.52,+0.51%,1630700
12,MMM,3M Company,177.69,-0.93,-0.52%,595893
13,VZ,Verizon Communications Inc.,59.95,-0.32,-0.53%,4751787
14,DIS,The Walt Disney Company,146.48,0.83,+0.57%,2452338
15,WMT,Walmart Inc.,116.94,-0.71,-0.60%,1802994
16,CSCO,"Cisco Systems, Inc.",47.44,-0.35,-0.74%,4279942
17,TRV,"The Travelers Companies, Inc.",136.15,-1.02,-0.74%,328177
18,HD,"The Home Depot, Inc.",218.14,-1.82,-0.83%,1333257
19,UNH,UnitedHealth Group Incorporated,288.77,-2.78,-0.95%,773618
20,WBA,"Walgreens Boots Alliance, Inc.",59.02,-0.57,-0.96%,1025618
21,CAT,Caterpillar Inc.,146.88,-1.46,-0.98%,850784
22,DOW,Dow Inc.,52.74,0.53,+1.02%,1042199
23,INTC,Intel Corporation,59.29,-0.64,-1.07%,7959886
24,JPM,JPMorgan Chase & Co.,136.72,-1.51,-1.09%,3651181
25,GS,"The Goldman Sachs Group, Inc.",236.90,2.95,+1.26%,2028732
26,XOM,Exxon Mobil Corporation,69.82,-1.05,-1.47%,4316410
27,CVX,Chevron Corporation,118.34,-2.26,-1.87%,2774860
28,MRK,"Merck & Co., Inc.",89.65,-1.99,-2.17%,4540542
29,BA,The Boeing Company,342.32,8.58,+2.57%,5112063

In [4]:
# Dow Stocks 1yr Prices and Daily Returns DataFrame

dow_stocks = dow_components_table["Symbol"]
# dow_company = dow_components_table["Company Name"]
market_basket = "DIA"

base_url = "https://sandbox.iexapis.com/stable/stock/"

# Query link for market API call (1 Year Data)
market_url = base_url + market_basket + "/chart/1y?token=" + api_token

    # JSON Response for market data
iex_market_response = requests.get(market_url).json()


# DataFrame for Market Data
market_date = []
market_close = []

for response in iex_market_response:
    market_date.append(response["date"])
    market_close.append(response["close"])

dow_df = pd.DataFrame({"Date": market_date,
                       "DIA": market_close})

dow_df["DIA_log_returns"] = (np.log(dow_df["DIA"]) - np.log(dow_df["DIA"].shift(1)))

dow_df

           Date     DIA  DIA_log_returns
0    2019-01-07  236.47              NaN
1    2019-01-08  238.12         0.006953
2    2019-01-09  247.65         0.039242
3    2019-01-10  241.00        -0.027220
4    2019-01-11  243.67         0.011018
..          ...     ...              ...
247  2019-12-30  288.76        -0.038287
248  2019-12-31  287.50        -0.004373
249  2020-01-02  303.02         0.052576
250  2020-01-03  298.79        -0.014058
251  2020-01-06  296.31        -0.008335

[252 rows x 3 columns]

In [6]:
# Function to return Stock 1yr Prices and Daily Returns

def returns(stock):
    
    base_url = "https://sandbox.iexapis.com/stable/stock/"
    
    # Query link for stock API call (1 Year Data)
    stock_url = base_url + stock + "/chart/1y?token=" + api_token   
    
    # JSON Response for stock data
    iex_stock_response = requests.get(stock_url).json()
    
    # DataFrame for Stock Data
    stock_date = []
    stock_close = []
    stock_returns = []

    # Interate through API Reponse
    for response in iex_stock_response:
        stock_date.append(response["date"])
        stock_close.append(response["close"])
        
    # Built Stock data Dataframe
    stock_data = pd.DataFrame({"Date": stock_date,
                           str(stock): stock_close})
    
    # To add column with daily returns
    stock_return_str = str(stock) + "_" + "log_returns"
    
    # Calculate Daily Returns
    stock_data[stock_return_str] = (np.log(stock_data[str(stock)]) - np.log(stock_data[str(stock)].shift(1)))  
    
    # Return Pandas Dataframe 
    return stock_data
    

# Test Function
returns("AAPL")

           Date    AAPL  AAPL_log_returns
0    2019-01-07  151.47               NaN
1    2019-01-08  156.41          0.032093
2    2019-01-09  156.96          0.003510
3    2019-01-10  154.10         -0.018389
4    2019-01-11  154.30          0.001297
..          ...     ...               ...
247  2019-12-30  303.19          0.012245
248  2019-12-31  307.27          0.013367
249  2020-01-02  302.39         -0.016009
250  2020-01-03  307.59          0.017050
251  2020-01-06  304.20         -0.011082

[252 rows x 3 columns]

In [7]:
# Interate through dow component stocks to return pandas dataframes for each component
dataframes = []

for stock in dow_stocks:
    stock_dataframe = returns(stock)
    dataframes.append(stock_dataframe)
    
dataframes

[           Date    AAPL  AAPL_log_returns
 0    2019-01-07  149.86               NaN
 1    2019-01-08  152.55          0.017791
 2    2019-01-09  160.29          0.049492
 3    2019-01-10  154.80         -0.034851
 4    2019-01-11  159.41          0.029346
 ..          ...     ...               ...
 247  2019-12-30  295.62          0.016783
 248  2019-12-31  293.85         -0.006005
 249  2020-01-02  313.42          0.064475
 250  2020-01-03  307.61         -0.018711
 251  2020-01-06  311.30          0.011924

 [252 rows x 3 columns],            Date    MSFT  MSFT_log_returns
 0    2019-01-07  105.98               NaN
 1    2019-01-08  102.90         -0.029493
 2    2019-01-09  107.65          0.045128
 3    2019-01-10  103.70         -0.037383
 4    2019-01-11  107.10          0.032261
 ..          ...     ...               ...
 247  2019-12-30  161.90         -0.020723
 248  2019-12-31  162.30          0.002468
 249  2020-01-02  161.74         -0.003456
 250  2020-01-03  163.44          0.010456
 251  2020-01-06  166.37          0.017768

 [252 rows x 3 columns],            Date     JNJ  JNJ_log_returns
 0    2019-01-07  130.52              NaN
 1    2019-01-08  134.47         0.029815
 2    2019-01-09  132.29        -0.016345
 3    2019-01-10  134.21         0.014409
 4    2019-01-11  133.50        -0.005304
 ..          ...     ...              ...
 247  2019-12-30  150.70         0.016593
 248  2019-12-31  147.47        -0.021666
 249  2020-01-02  151.47         0.026763
 250  2020-01-03  145.53        -0.040005
 251  2020-01-06  147.20         0.011410

 [252 rows x 3 columns],            Date    PFE  PFE_log_returns
 0    2019-01-07  44.33              NaN
 1    2019-01-08  44.83         0.011216
 2    2019-01-09  44.14        -0.015511
 3    2019-01-10  44.38         0.005423
 4    2019-01-11  43.76        -0.014069
 ..          ...    ...              ...
 247  2019-12-30  40.21         0.011003
 248  2019-12-31  40.70         0.012112
 249  2020-01-02  39.71        -0.024625
 250  2020-01-03  40.33         0.015493
 251  2020-01-06  39.19        -0.028674

 [252 rows x 3 columns],            Date     AXP  AXP_log_returns
 0    2019-01-07   99.28              NaN
 1    2019-01-08   99.27        -0.000101
 2    2019-01-09   99.66         0.003921
 3    2019-01-10  101.44         0.017703
 4    2019-01-11  100.81        -0.006230
 ..          ...     ...              ...
 247  2019-12-30  129.00        -0.017596
 248  2019-12-31  126.01        -0.023451
 249  2020-01-02  128.29         0.017932
 250  2020-01-03  129.90         0.012472
 251  2020-01-06  125.14        -0.037332

 [252 rows x 3 columns],            Date       V  V_log_returns
 0    2019-01-07  138.27            NaN
 1    2019-01-08  140.80       0.018132
 2    2019-01-09  145.31       0.031529
 3    2019-01-10  144.91      -0.002757
 4    2019-01-11  142.87      -0.014178
 ..          ...     ...            ...
 247  2019-12-30  194.35       0.009876
 248  2019-12-31  191.60      -0.014251
 249  2020-01-02  193.00       0.007280
 250  2020-01-03  193.00       0.000000
 251  2020-01-06  191.05      -0.010155

 [252 rows x 3 columns],            Date      PG  PG_log_returns
 0    2019-01-07   96.10             NaN
 1    2019-01-08   94.98       -0.011723
 2    2019-01-09   95.20        0.002314
 3    2019-01-10   91.44       -0.040297
 4    2019-01-11   92.94        0.016271
 ..          ...     ...             ...
 247  2019-12-30  126.83       -0.037299
 248  2019-12-31  125.20       -0.012935
 249  2020-01-02  124.34       -0.006893
 250  2020-01-03  128.13        0.030026
 251  2020-01-06  123.58       -0.036157

 [252 rows x 3 columns],            Date     KO  KO_log_returns
 0    2019-01-07  48.76             NaN
 1    2019-01-08  47.60       -0.024078
 2    2019-01-09  47.29       -0.006534
 3    2019-01-10  49.22        0.040001
 4    2019-01-11  48.35       -0.017834
 ..          ...    ...             ...
 247  2019-12-30  57.65        0.007137
 248  2019-12-31  56.57       -0.018911
 249  2020-01-02  56.25       -0.005673
 250  2020-01-03  57.33        0.019018
 251  2020-01-06  54.70       -0.046960

 [252 rows x 3 columns],            Date     IBM  IBM_log_returns
 0    2019-01-07  122.54              NaN
 1    2019-01-08  121.33        -0.009923
 2    2019-01-09  124.68         0.027236
 3    2019-01-10  124.78         0.000802
 4    2019-01-11  126.26         0.011791
 ..          ...     ...              ...
 247  2019-12-30  138.32        -0.025764
 248  2019-12-31  134.25        -0.029866
 249  2020-01-02  140.57         0.046002
 250  2020-01-03  135.04        -0.040135
 251  2020-01-06  137.70         0.019506

 [252 rows x 3 columns],            Date     MCD  MCD_log_returns
 0    2019-01-07  182.23              NaN
 1    2019-01-08  188.00         0.031172
 2    2019-01-09  182.77        -0.028213
 3    2019-01-10  188.24         0.029489
 4    2019-01-11  186.93        -0.006984
 ..          ...     ...              ...
 247  2019-12-30  198.82        -0.013538
 248  2019-12-31  202.64         0.019031
 249  2020-01-02  205.67         0.014842
 250  2020-01-03  205.93         0.001263
 251  2020-01-06  206.43         0.002425

 [252 rows x 3 columns],            Date     UTX  UTX_log_returns
 0    2019-01-07  109.48              NaN
 1    2019-01-08  110.00         0.004738
 2    2019-01-09  110.64         0.005801
 3    2019-01-10  115.74         0.045065
 4    2019-01-11  112.64        -0.027149
 ..          ...     ...              ...
 247  2019-12-30  153.99         0.003448
 248  2019-12-31  152.61        -0.009002
 249  2020-01-02  157.22         0.029760
 250  2020-01-03  154.31        -0.018683
 251  2020-01-06  157.37         0.019636

 [252 rows x 3 columns],            Date     NKE  NKE_log_returns
 0    2019-01-07   78.03              NaN
 1    2019-01-08   79.27         0.015766
 2    2019-01-09   77.36        -0.024390
 3    2019-01-10   79.77         0.030678
 4    2019-01-11   76.52        -0.041595
 ..          ...     ...              ...
 247  2019-12-30  104.40         0.006149
 248  2019-12-31  101.70        -0.026202
 249  2020-01-02  105.30         0.034786
 250  2020-01-03  104.54        -0.007244
 251  2020-01-06  101.97        -0.024891

 [252 rows x 3 columns],            Date     MMM  MMM_log_returns
 0    2019-01-07  192.69              NaN
 1    2019-01-08  194.01         0.006827
 2    2019-01-09  201.10         0.035893
 3    2019-01-10  196.50        -0.023140
 4    2019-01-11  198.19         0.008564
 ..          ...     ...              ...
 247  2019-12-30  183.21         0.029411
 248  2019-12-31  184.96         0.009507
 249  2020-01-02  189.00         0.021607
 250  2020-01-03  186.80        -0.011708
 251  2020-01-06  178.63        -0.044722

 [252 rows x 3 columns],            Date     VZ  VZ_log_returns
 0    2019-01-07  57.83             NaN
 1    2019-01-08  60.84        0.050740
 2    2019-01-09  57.87       -0.050048
 3    2019-01-10  59.60        0.029456
 4    2019-01-11  58.09       -0.025662
 ..          ...    ...             ...
 247  2019-12-30  63.33       -0.012553
 248  2019-12-31  63.70        0.005825
 249  2020-01-02  63.55       -0.002358
 250  2020-01-03  61.20       -0.037680
 251  2020-01-06  62.04        0.013632

 [252 rows x 3 columns],            Date     DIS  DIS_log_returns
 0    2019-01-07  114.80              NaN
 1    2019-01-08  113.23        -0.013770
 2    2019-01-09  114.13         0.007917
 3    2019-01-10  115.30         0.010199
 4    2019-01-11  116.63         0.011469
 ..          ...     ...              ...
 247  2019-12-30  146.33        -0.025304
 248  2019-12-31  148.77         0.016537
 249  2020-01-02  154.20         0.035849
 250  2020-01-03  153.20        -0.006506
 251  2020-01-06  146.95        -0.041652

 [252 rows x 3 columns],            Date     WMT  WMT_log_returns
 0    2019-01-07   97.02              NaN
 1    2019-01-08   96.40        -0.006411
 2    2019-01-09   99.35         0.030143
 3    2019-01-10   99.46         0.001107
 4    2019-01-11   99.53         0.000704
 ..          ...     ...              ...
 247  2019-12-30  124.10         0.013058
 248  2019-12-31  124.29         0.001530
 249  2020-01-02  119.62        -0.038297
 250  2020-01-03  123.32         0.030463
 251  2020-01-06  117.98        -0.044267

 [252 rows x 3 columns],            Date   CSCO  CSCO_log_returns
 0    2019-01-07  44.28               NaN
 1    2019-01-08  44.23         -0.001130
 2    2019-01-09  44.90          0.015035
 3    2019-01-10  43.30         -0.036285
 4    2019-01-11  45.62          0.052194
 ..          ...    ...               ...
 247  2019-12-30  48.53          0.000412
 248  2019-12-31  49.04          0.010454
 249  2020-01-02  49.09          0.001019
 250  2020-01-03  48.52         -0.011679
 251  2020-01-06  49.50          0.019997

 [252 rows x 3 columns],            Date     TRV  TRV_log_returns
 0    2019-01-07  122.50              NaN
 1    2019-01-08  119.27        -0.026721
 2    2019-01-09  122.48         0.026558
 3    2019-01-10  125.16         0.021645
 4    2019-01-11  121.11        -0.032894
 ..          ...     ...              ...
 247  2019-12-30  141.42         0.015104
 248  2019-12-31  142.53         0.007818
 249  2020-01-02  142.38        -0.001053
 250  2020-01-03  141.27        -0.007827
 251  2020-01-06  139.57        -0.012107

 [252 rows x 3 columns],            Date      HD  HD_log_returns
 0    2019-01-07  183.70             NaN
 1    2019-01-08  178.60       -0.028155
 2    2019-01-09  186.72        0.044462
 3    2019-01-10  181.27       -0.029623
 4    2019-01-11  187.91        0.035975
 ..          ...     ...             ...
 247  2019-12-30  217.63       -0.042902
 248  2019-12-31  224.13        0.029430
 249  2020-01-02  222.45       -0.007524
 250  2020-01-03  229.09        0.029413
 251  2020-01-06  230.51        0.006179

 [252 rows x 3 columns],            Date     UNH  UNH_log_returns
 0    2019-01-07  240.70              NaN
 1    2019-01-08  255.05         0.057908
 2    2019-01-09  249.18        -0.023284
 3    2019-01-10  249.93         0.003005
 4    2019-01-11  250.45         0.002078
 ..          ...     ...              ...
 247  2019-12-30  305.95        -0.007652
 248  2019-12-31  296.02        -0.032995
 249  2020-01-02  306.10         0.033485
 250  2020-01-03  297.58        -0.028229
 251  2020-01-06  299.81         0.007466

 [252 rows x 3 columns],            Date    WBA  WBA_log_returns
 0    2019-01-07  70.76              NaN
 1    2019-01-08  71.60         0.011801
 2    2019-01-09  74.64         0.041581
 3    2019-01-10  73.39        -0.016889
 4    2019-01-11  73.13        -0.003549
 ..          ...    ...              ...
 247  2019-12-30  60.94         0.018550
 248  2019-12-31  59.07        -0.031167
 249  2020-01-02  61.06         0.033134
 250  2020-01-03  60.14        -0.015182
 251  2020-01-06  60.17         0.000499

 [252 rows x 3 columns],            Date     CAT  CAT_log_returns
 0    2019-01-07  128.61              NaN
 1    2019-01-08  133.16         0.034767
 2    2019-01-09  134.03         0.006512
 3    2019-01-10  136.55         0.018627
 4    2019-01-11  135.30        -0.009196
 ..          ...     ...              ...
 247  2019-12-30  151.79         0.002441
 248  2019-12-31  152.56         0.005060
 249  2020-01-02  155.50         0.019088
 250  2020-01-03  148.76        -0.044311
 251  2020-01-06  150.61         0.012359

 [252 rows x 3 columns],            Date    DOW  DOW_log_returns
 0    2019-04-02  59.02              NaN
 1    2019-04-03  57.81        -0.020715
 2    2019-04-04  60.26         0.041507
 3    2019-04-05  57.76        -0.042372
 4    2019-04-08  58.64         0.015121
 ..          ...    ...              ...
 188  2019-12-30  55.02        -0.014615
 189  2019-12-31  55.00        -0.000364
 190  2020-01-02  55.20         0.003630
 191  2020-01-03  53.08        -0.039163
 192  2020-01-06  53.38         0.005636

 [193 rows x 3 columns],            Date   INTC  INTC_log_returns
 0    2019-01-07  48.31               NaN
 1    2019-01-08  49.15          0.017238
 2    2019-01-09  49.40          0.005074
 3    2019-01-10  50.93          0.030502
 4    2019-01-11  49.67         -0.025051
 ..          ...    ...               ...
 247  2019-12-30  59.79         -0.030310
 248  2019-12-31  62.37          0.042246
 249  2020-01-02  62.58          0.003361
 250  2020-01-03  61.70         -0.014162
 251  2020-01-06  62.73          0.016556

 [252 rows x 3 columns],            Date     JPM  JPM_log_returns
 0    2019-01-07  102.35              NaN
 1    2019-01-08  103.63         0.012429
 2    2019-01-09  101.10        -0.024717
 3    2019-01-10  100.95        -0.001485
 4    2019-01-11  103.78         0.027648
 ..          ...     ...              ...
 247  2019-12-30  138.93        -0.002875
 248  2019-12-31  144.70         0.040692
 249  2020-01-02  146.19         0.010245
 250  2020-01-03  144.62        -0.010798
 251  2020-01-06  138.37        -0.044178

 [252 rows x 3 columns],            Date      GS  GS_log_returns
 0    2019-01-07  178.57             NaN
 1    2019-01-08  180.38        0.010085
 2    2019-01-09  178.62       -0.009805
 3    2019-01-10  181.00        0.013236
 4    2019-01-11  185.55        0.024827
 ..          ...     ...             ...
 247  2019-12-30  240.00        0.038048
 248  2019-12-31  240.70        0.002912
 249  2020-01-02  242.75        0.008481
 250  2020-01-03  239.86       -0.011977
 251  2020-01-06  239.36       -0.002087

 [252 rows x 3 columns],            Date    XOM  XOM_log_returns
 0    2019-01-07  71.89              NaN
 1    2019-01-08  73.26         0.018878
 2    2019-01-09  74.22         0.013019
 3    2019-01-10  74.84         0.008319
 4    2019-01-11  73.41        -0.019292
 ..          ...    ...              ...
 247  2019-12-30  72.01        -0.006782
 248  2019-12-31  71.47        -0.007527
 249  2020-01-02  73.80         0.032081
 250  2020-01-03  72.81        -0.013505
 251  2020-01-06  73.36         0.007526

 [252 rows x 3 columns],            Date     CVX  CVX_log_returns
 0    2019-01-07  112.68              NaN
 1    2019-01-08  112.67        -0.000089
 2    2019-01-09  114.78         0.018554
 3    2019-01-10  117.97         0.027413
 4    2019-01-11  117.92        -0.000424
 ..          ...     ...              ...
 247  2019-12-30  121.78        -0.003443
 248  2019-12-31  125.94         0.033589
 249  2020-01-02  126.52         0.004595
 250  2020-01-03  123.78        -0.021895
 251  2020-01-06  124.30         0.004192

 [252 rows x 3 columns],            Date    MRK  MRK_log_returns
 0    2019-01-07  77.96              NaN
 1    2019-01-08  79.14         0.015023
 2    2019-01-09  76.31        -0.036414
 3    2019-01-10  74.66        -0.021860
 4    2019-01-11  76.40         0.023038
 ..          ...    ...              ...
 247  2019-12-30  91.86         0.002834
 248  2019-12-31  91.07        -0.008637
 249  2020-01-02  92.18         0.012115
 250  2020-01-03  91.58        -0.006530
 251  2020-01-06  92.48         0.009779

 [252 rows x 3 columns],            Date      BA  BA_log_returns
 0    2019-01-07  335.45             NaN
 1    2019-01-08  355.49        0.058024
 2    2019-01-09  358.27        0.007790
 3    2019-01-10  369.74        0.031513
 4    2019-01-11  370.00        0.000703
 ..          ...     ...             ...
 247  2019-12-30  329.90       -0.030744
 248  2019-12-31  327.04       -0.008707
 249  2020-01-02  345.79        0.055749
 250  2020-01-03  336.40       -0.027531
 251  2020-01-06  336.20       -0.000595

 [252 rows x 3 columns]]

In [8]:
########  Merge all Stock Dateframes

stock_dataframes = list(dataframes)
               
stock_returns_dfs = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],
                                            how='outer'), stock_dataframes) 
stock_returns_dfs

,Date,AAPL,AAPL_log_returns,MSFT,MSFT_log_returns,JNJ,JNJ_log_returns,PFE,PFE_log_returns,AXP,...,GS,GS_log_returns,XOM,XOM_log_returns,CVX,CVX_log_returns,MRK,MRK_log_returns,BA,BA_log_returns
0,2019-01-07,149.86,NaN,105.98,NaN,130.52,NaN,44.33,NaN,99.28,...,178.57,NaN,71.89,NaN,112.68,NaN,77.96,NaN,335.45,NaN
1,2019-01-08,152.55,0.017791,102.90,-0.029493,134.47,0.029815,44.83,0.011216,99.27,...,180.38,0.010085,73.26,0.018878,112.67,-0.000089,79.14,0.015023,355.49,0.058024
2,2019-01-09,160.29,0.049492,107.65,0.045128,132.29,-0.016345,44.14,-0.015511,99.66,...,178.62,-0.009805,74.22,0.013019,114.78,0.018554,76.31,-0.036414,358.27,0.007790
3,2019-01-10,154.80,-0.034851,103.70,-0.037383,134.21,0.014409,44.38,0.005423,101.44,...,181.00,0.013236,74.84,0.008319,117.97,0.027413,74.66,-0.021860,369.74,0.031513
4,2019-01-11,159.41,0.029346,107.10,0.032261,133.50,-0.005304,43.76,-0.014069,100.81,...,185.55,0.024827,73.41,-0.019292,117.92,-0.000424,76.40,0.023038,370.00,0.000703
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2019-12-30,295.62,0.016783,161.90,-0.020723,150.70,0.016593,40.21,0.011003,129.00,...,240.00,0.038048,72.01,-0.006782,121.78,-0.003443,91.86,0.002834,329.90,-0.030744
248,2019-12-31,293.85,-0.006005,162.30,0.002468,147.47,-0.021666,40.70,0.012112,126.01,...,240.70,0.002912,71.47,-0.007527,125.94,0.033589,91.07,-0.008637,327.04,-0.008707
249,2020-01-02,313.42,0.064475,161.74,-0.003456,151.47,0.026763,39.71,-0.024625,128.29,...,242.75,0.008481,73.80,0.032081,126.52,0.004595,92.18,0.012115,345.79,0.055749
250,2020-01-03,307.61,-0.018711,163.44,0.010456,145.53,-0.040005,40.33,0.015493,129.90,...,239.86,-0.011977,72.81,-0.013505,123.78,-0.021895,91.58,-0.006530,336.40,-0.027531
251,2020-01-06,311.30,0.011924,166.37,0.017768,147.20,0.011410,39.19,-0.028674,125.14,...,239.36,-0.002087,73.36,0.007526,124.30,0.004192,92.48,0.009779,336.20,-0.000595

In [9]:
# Merge Stocks Dataframe with Market Dataframe
dow_returns = pd.merge(dow_df, stock_returns_dfs, on="Date", how="inner")
dow_returns_df = dow_returns.set_index("Date")
final_dow_df = dow_returns_df.iloc[1:]
final_dow_df

,DIA,DIA_log_returns,AAPL,AAPL_log_returns,MSFT,MSFT_log_returns,JNJ,JNJ_log_returns,PFE,PFE_log_returns,...,GS,GS_log_returns,XOM,XOM_log_returns,CVX,CVX_log_returns,MRK,MRK_log_returns,BA,BA_log_returns
Date,,,,,,,,,,,,,,,,,,,,,
2019-01-08,238.12,0.006953,152.55,0.017791,102.90,-0.029493,134.47,0.029815,44.83,0.011216,...,180.38,0.010085,73.26,0.018878,112.67,-0.000089,79.14,0.015023,355.49,0.058024
2019-01-09,247.65,0.039242,160.29,0.049492,107.65,0.045128,132.29,-0.016345,44.14,-0.015511,...,178.62,-0.009805,74.22,0.013019,114.78,0.018554,76.31,-0.036414,358.27,0.007790
2019-01-10,241.00,-0.027220,154.80,-0.034851,103.70,-0.037383,134.21,0.014409,44.38,0.005423,...,181.00,0.013236,74.84,0.008319,117.97,0.027413,74.66,-0.021860,369.74,0.031513
2019-01-11,243.67,0.011018,159.41,0.029346,107.10,0.032261,133.50,-0.005304,43.76,-0.014069,...,185.55,0.024827,73.41,-0.019292,117.92,-0.000424,76.40,0.023038,370.00,0.000703
2019-01-14,249.79,0.024806,157.00,-0.015234,103.73,-0.031972,130.44,-0.023188,43.04,-0.016590,...,185.08,-0.002536,73.77,0.004892,112.56,-0.046520,76.95,0.007173,355.79,-0.039162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-30,288.76,-0.038287,295.62,0.016783,161.90,-0.020723,150.70,0.016593,40.21,0.011003,...,240.00,0.038048,72.01,-0.006782,121.78,-0.003443,91.86,0.002834,329.90,-0.030744
2019-12-31,287.50,-0.004373,293.85,-0.006005,162.30,0.002468,147.47,-0.021666,40.70,0.012112,...,240.70,0.002912,71.47,-0.007527,125.94,0.033589,91.07,-0.008637,327.04,-0.008707
2020-01-02,303.02,0.052576,313.42,0.064475,161.74,-0.003456,151.47,0.026763,39.71,-0.024625,...,242.75,0.008481,73.80,0.032081,126.52,0.004595,92.18,0.012115,345.79,0.055749
2020-01-03,298.79,-0.014058,307.61,-0.018711,163.44,0.010456,145.53,-0.040005,40.33,0.015493,...,239.86,-0.011977,72.81,-0.013505,123.78,-0.021895,91.58,-0.006530,336.40,-0.027531
2020-01-06,296.31,-0.008335,311.30,0.011924,166.37,0.017768,147.20,0.011410,39.19,-0.028674,...,239.36,-0.002087,73.36,0.007526,124.30,0.004192,92.48,0.009779,336.20,-0.000595

In [10]:
# Create list of symbols for Statistics DataFrame
symbol_list = ["DIA"]
for stock in dow_stocks:
    symbol_list.append(stock)

# Build Statistics Dataframe
stat_data = pd.DataFrame({"Stock": symbol_list,
                          "Mean_of_Daily_Returns": ""})

# Preview
stat_data.head()

  Stock Mean_of_Daily_Returns
0   DIA
1  AAPL
2  MSFT
3   JNJ
4   PFE

In [11]:
# Number of trading days in sample
trading_days = len(iex_market_response)
trading_days

252

In [13]:
# # Iterating and Printing Column Values Preview

# for columnName, columnData in final_dow_df.iteritems():
#    #print('Column Name : ', columnName)
#    #print('Column Contents : ', columnData.values)

In [14]:
# Overall Market List of Daily Returns and Market Variance variable

market_returns = final_dow_df["DIA_log_returns"]

market_variance = final_dow_df["DIA_log_returns"].var()

print(market_variance)

0.0004347035997031569

In [24]:
# Iterating Columns for statistical data

means = []
variances = []
standard_deviations = []
annual_sds = []
covariances = []
betas = []
coefficients = []
systematic_risks = []
unsystematic_risks = []

for columnName, columnData in final_dow_df.iteritems():

    if columnName in list(symbol_list):
        pass
    else: 
        # Calculate Stock Returns Mean
        mean = columnData.mean()
        means.append(mean)
        
        # Calculate Stock Returns Variance
        var = columnData.var()
        variances.append(var)
        
        # Calculate Stock Returns Standard Deviations
        sd = math.sqrt(var)
        standard_deviations.append(sd) 
        
        # Calculate Annualized Standard Deviations
        sd_annual = sd * math.sqrt(trading_days)
        annual_sds.append(sd_annual)
        
        # Calculate Covariance
        covars = np.cov(columnData, market_returns, ddof=1)[0][1]
        covariances.append(covars)
        
        # Beta = Covariance / Market Variance 
        beta = covars / market_variance
        betas.append(round(beta, 3))
        
        #Calculate Correlation Coefficients
        corr_coef = np.corrcoef(columnData, market_returns, ddof=1)[0][1]
        coefficients.append(round(corr_coef, 3))
        
        # Total Risk
        total_risk = var
        
        # Calculate Systematic Risk
        systematic = ((np.square(beta) * market_variance) / total_risk) * 100
        systematic_risks.append(round(systematic, 3))
        
        # Calculate Systematic Risk
        unsystematic = 100 - systematic
        unsystematic_risks.append(round(unsystematic, 3))
        

print("----------------------------------------------")
print("Means: ")        
print(means)
print("----------------------------------------------")
print("Variances: ")  
print(variances)
print("----------------------------------------------")
print("Standard Deviations: ")  
print(standard_deviations)
print("----------------------------------------------")
print("Annualized Standard Deviations: ")  
print(annual_sds)    
print("----------------------------------------------")
print("Covariances: ")  
print(covariances)  
print("----------------------------------------------")
print("Betas: ")  
print(betas)  
print("----------------------------------------------")
print("Coefficients: ")  
print(coefficients) 
print("----------------------------------------------")
print("Systematic Risks: ")  
print(systematic_risks) 
print("----------------------------------------------")
print("Unsystematic Risks: ")  
print(unsystematic_risks) 
print("----------------------------------------------")

----------------------------------------------
Means:
[0.0008987444366397525, 0.0029125719223561672, 0.001796668631900538, 0.0004791463528671574, -0.0004909961615355468, 0.0009222668114496663, 0.0012881548943919625, 0.0010019896560023395, 0.0004579816924895004, 0.00046470079058605926, 0.0004967798660738409, 0.0014456487507581465, 0.0010660768296711757, -0.0003018567827769644, 0.00027996679736339133, 0.0009836689600775292, 0.0007792748038161704, 0.0004439823176661704, 0.0005197419822142273, 0.0009043436383366768, 0.0008748908202930946, -0.0006458963348977089, 0.0006291200993855065, -0.0005231261746792467, 0.0010406423248698646, 0.0012013264724063508, 0.0011672829226178456, 8.064404363517406e-05, 0.00039102014146810216, 0.0006804642640825015, 8.897637313221637e-06]
----------------------------------------------
Variances:
[0.0004347035997031569, 0.0005979633272137159, 0.0005129719893560393, 0.0004869439711329124, 0.000504515009434183, 0.00045533555877325327, 0.0005156500069639863, 0.000455792205205795, 0.0005083339486254189, 0.0004908411720345885, 0.0004498036846372758, 0.0006363622719607532, 0.0005634819719290991, 0.0005829995581332578, 0.000538820984516758, 0.0005053097888477095, 0.0005118299948382621, 0.0006538742223941191, 0.00044807805694495404, 0.0005246459739246007, 0.0006288727356676089, 0.0006641716780546982, 0.0007066689204326421, 0.0007940944858177614, 0.0006287858358384624, 0.0005630534836192533, 0.0005822683425269826, 0.0005611106973727964, 0.0004986319494232134, 0.00046534919052879185, 0.0007144087049817731]
----------------------------------------------
Standard Deviations:
[0.020849546750544887, 0.024453288678901983, 0.02264888494730015, 0.02206680699904072, 0.022461411563705944, 0.02133859317699396, 0.02270792828427962, 0.021349290508253314, 0.022546262409220266, 0.022154935613415548, 0.021208575733350783, 0.025226221912144377, 0.023737775210181326, 0.024145383785172225, 0.023212517840957236, 0.022479096708891786, 0.022623660067245133, 0.02557096444004643, 0.021167854330209145, 0.022905151689622157, 0.025077335099001428, 0.025771528438466706, 0.026583245107259613, 0.028179682145435234, 0.025075602402304564, 0.02372874804154769, 0.024130237100513176, 0.023687775272760343, 0.022330068280755736, 0.02157195379488821, 0.02672842503743483]
----------------------------------------------
Annualized Standard Deviations:
[0.3309762939021397, 0.38818392349227504, 0.35953990226082266, 0.3502997012923276, 0.35656385455821815, 0.3387396652458342, 0.36047718617816105, 0.33890948011506017, 0.3579108199728049, 0.35169869967447465, 0.336675702313953, 0.40045385818357376, 0.3768254993045627, 0.38329608483466276, 0.3684872970649369, 0.356844597534589, 0.35913946970396066, 0.40592647615463323, 0.3360292700794507, 0.36360801067770687, 0.39809035329713466, 0.40911033092527005, 0.42199593356930093, 0.44733858589001224, 0.3980628475897902, 0.37668219744507686, 0.383055638669893, 0.37603177490465445, 0.3544788445798279, 0.3424441502103015, 0.424300593512909]
----------------------------------------------
Covariances:
[0.0004347035997031569, 0.00011845023732859107, 9.697050665923485e-06, 2.2514310205737794e-05, 8.840481622634224e-05, 6.925440635814177e-05, 6.427162588294724e-05, 5.9975004676974825e-05, -2.3759889991800313e-05, 1.8628167396848418e-06, 3.0282092785748976e-05, 0.00012757023130293086, 3.5115105711022725e-05, 0.0001069291258905951, 4.241081705922284e-05, 4.629096667393145e-05, 1.8490980247835625e-05, 8.676007038777685e-05, 1.548142610479644e-06, 4.5518967897951424e-05, 5.631584449193313e-05, 0.00012422755533754695, 0.00010485167834793696, nan, 4.177143682507193e-05, 9.522220861459929e-05, -9.738886815774703e-06, 0.0001377685779490451, -1.170810756650222e-06, 9.074404004418644e-05, 1.5275836687057564e-05]
----------------------------------------------
Betas:
[1.0, 0.272, 0.022, 0.052, 0.203, 0.159, 0.148, 0.138, -0.055, 0.004, 0.07, 0.293, 0.081, 0.246, 0.098, 0.106, 0.043, 0.2, 0.004, 0.105, 0.13, 0.286, 0.241, nan, 0.096, 0.219, -0.022, 0.317, -0.003, 0.209, 0.035]
----------------------------------------------
Coefficients:
[1.0, 0.232, 0.021, 0.049, 0.189, 0.156, 0.136, 0.135, -0.051, 0.004, 0.068, 0.243, 0.071, 0.212, 0.088, 0.099, 0.039, 0.163, 0.004, 0.095, 0.108, 0.231, 0.189, nan, 0.08, 0.192, -0.019, 0.279, -0.003, 0.202, 0.027]
----------------------------------------------
Systematic Risks:
[100.0, 5.398, 0.042, 0.239, 3.564, 2.423, 1.843, 1.815, 0.255, 0.002, 0.469, 5.883, 0.503, 4.512, 0.768, 0.976, 0.154, 2.648, 0.001, 0.909, 1.16, 5.345, 3.579, nan, 0.638, 3.705, 0.037, 7.781, 0.001, 4.071, 0.075]
----------------------------------------------
Unsystematic Risks:
[0.0, 94.602, 99.958, 99.761, 96.436, 97.577, 98.157, 98.185, 99.745, 99.998, 99.531, 94.117, 99.497, 95.488, 99.232, 99.024, 99.846, 97.352, 99.999, 99.091, 98.84, 94.655, 96.421, nan, 99.362, 96.295, 99.963, 92.219, 99.999, 95.929, 99.925]
----------------------------------------------

C:\Users\deepe\Anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:43: DeprecationWarning: bias and ddof have no effect and are deprecated

In [25]:
# Append Statistics DataFrame with values
stat_data["Mean_of_Daily_Returns"] = means
stat_data["Variance_of_Daily_Returns"] = variances
stat_data["Standard_Deviation_of_Daily_Returns"] = standard_deviations
stat_data["Annual_Standard_Deviation"] = annual_sds
stat_data["Covariance"] = covariances
stat_data["Beta"] = betas
stat_data["Correlation_Coefficient"] = coefficients

stat_data["Systematic_Risk (%)"] = systematic_risks
stat_data["Unsystematic_Risk (%)"] = unsystematic_risks

# DataFrame for Dow Components statistical data 
stat_data

# Note that the statistics for the symbol "DOW" have Null Values because data for the entire year cannot be pulled from IEX

,Stock,Mean_of_Daily_Returns,Variance_of_Daily_Returns,Standard_Deviation_of_Daily_Returns,Annual_Standard_Deviation,Covariance,Beta,Correlation_Coefficient,Systematic_Risk (%),Unsystematic_Risk (%)
0,DIA,0.000899,0.000435,0.020850,0.330976,0.000435,1.000,1.000,100.000,0.000
1,AAPL,0.002913,0.000598,0.024453,0.388184,0.000118,0.272,0.232,5.398,94.602
2,MSFT,0.001797,0.000513,0.022649,0.359540,0.000010,0.022,0.021,0.042,99.958
3,JNJ,0.000479,0.000487,0.022067,0.350300,0.000023,0.052,0.049,0.239,99.761
4,PFE,-0.000491,0.000505,0.022461,0.356564,0.000088,0.203,0.189,3.564,96.436
5,AXP,0.000922,0.000455,0.021339,0.338740,0.000069,0.159,0.156,2.423,97.577
6,V,0.001288,0.000516,0.022708,0.360477,0.000064,0.148,0.136,1.843,98.157
7,PG,0.001002,0.000456,0.021349,0.338909,0.000060,0.138,0.135,1.815,98.185
8,KO,0.000458,0.000508,0.022546,0.357911,-0.000024,-0.055,-0.051,0.255,99.745
9,IBM,0.000465,0.000491,0.022155,0.351699,0.000002,0.004,0.004,0.002,99.998
10,MCD,0.000497,0.000450,0.021209,0.336676,0.000030,0.070,0.068,0.469,99.531
11,UTX,0.001446,0.000636,0.025226,0.400454,0.000128,0.293,0.243,5.883,94.117
12,NKE,0.001066,0.000563,0.023738,0.376825,0.000035,0.081,0.071,0.503,99.497
13,MMM,-0.000302,0.000583,0.024145,0.383296,0.000107,0.246,0.212,4.512,95.488
14,VZ,0.000280,0.000539,0.023213,0.368487,0.000042,0.098,0.088,0.768,99.232
15,DIS,0.000984,0.000505,0.022479,0.356845,0.000046,0.106,0.099,0.976,99.024
16,WMT,0.000779,0.000512,0.022624,0.359139,0.000018,0.043,0.039,0.154,99.846
17,CSCO,0.000444,0.000654,0.025571,0.405926,0.000087,0.200,0.163,2.648,97.352
18,TRV,0.000520,0.000448,0.021168,0.336029,0.000002,0.004,0.004,0.001,99.999
19,HD,0.000904,0.000525,0.022905,0.363608,0.000046,0.105,0.095,0.909,99.091
20,UNH,0.000875,0.000629,0.025077,0.398090,0.000056,0.130,0.108,1.160,98.840
21,WBA,-0.000646,0.000664,0.025772,0.409110,0.000124,0.286,0.231,5.345,94.655
22,CAT,0.000629,0.000707,0.026583,0.421996,0.000105,0.241,0.189,3.579,96.421
23,DOW,-0.000523,0.000794,0.028180,0.447339,NaN,NaN,NaN,NaN,NaN
24,INTC,0.001041,0.000629,0.025076,0.398063,0.000042,0.096,0.080,0.638,99.362
25,JPM,0.001201,0.000563,0.023729,0.376682,0.000095,0.219,0.192,3.705,96.295
26,GS,0.001167,0.000582,0.024130,0.383056,-0.000010,-0.022,-0.019,0.037,99.963
27,XOM,0.000081,0.000561,0.023688,0.376032,0.000138,0.317,0.279,7.781,92.219
28,CVX,0.000391,0.000499,0.022330,0.354479,-0.000001,-0.003,-0.003,0.001,99.999
29,MRK,0.000680,0.000465,0.021572,0.342444,0.000091,0.209,0.202,4.071,95.929
30,BA,0.000009,0.000714,0.026728,0.424301,0.000015,0.035,0.027,0.075,99.925